### ISSUE TITLE
Dynamic index update

### ISSUE THREAD

**Issue by vadimkantorov** [aaalgo/kgraph#10]
Hi,

I'm retrieving nearest neighbors to generate mini-batches to train a neural network. A side effect is that embeddings of the data points are changing constantly. Can kgraph support dynamic updates of embeddings of data points?

I assume, though, that the distribution of the data does not change drastically, so helper structures splitting the input space may not need to be rebuilt.

Thanks!

**Comment by aaalgo** [comment]
KGraph doesn't support dynamic updating indexed data, and I have no plan to add such supports.  https://github.com/searchivarius/nmslib supports insertion, but not deletion as far as I know.

**Comment by vadimkantorov** [comment]
About the k-nn graph index in general, would you have thoughts on support for dynamic deletions / insertions?

**Comment by aaalgo** [comment]
In principle it's possible to maintain a dynamic k-nn graph: each insertion is essentially a k-nn search.
It will however make the implementation much more complicated, and might better be done in a new project.  I haven't find a strong need to implement this yet.

**Comment by vadimkantorov** [comment]
Thanks :) I guess for now I'll just rebuild the index periodically.

**Comment by DBWangWei** [comment]
Another choice is to implement an algorithm to support insertions with a good amortized complexity. 

The basic idea is to
- cache the newly inserted points in memory and build a sub-index for it. 
- when the sub-index is larger than memory, dump it to the disk. Each of such index is called generation 1 
- You set a parameter k, such that you do not allow k sub-indexes of the same generation. If you do, you merge them into a single sub-index and increase the generation number by 1. 

This is essentially the same algorithm implemented by Lucene (c.f., http://lucene.sourceforge.net/talks/pisa/)

This ensures that at any time there is only O(log_k (N/M)) sub-indexes, and that's the multiplicative factor introduced into the query complexity in order to support insertions.
