### ISSUE TITLE
Usage of Vector oracle

### ISSUE THREAD

**Issue by eclipse0922** [aaalgo/kgraph#11]
I need some help to use Kgraph and oracle.

I have Two data set. 
 A, B

Each data set has thousands of 30 dimension data.
A[30][N]  B[30][M]    N is not equal to M

I want to find the nearest neighbor(k=1) of A[30][i]  in B

and vice-versa.

So I made this vector oracle

`		
```
	        using typeECSAD = std::array<float, 30>;
               auto fn_l2_euclid = [](typeECSAD const &a, typeECSAD const &b)
 		{
 			float sum = 0.0f;
 			for (int i = 0; i < 30; i++)
 			{
 				sum += pow((a[i] - b[i]), 2);
 			}
 			sum = sqrt(sum);
 			return sum;
 		};
```
			
		using kgraph_ECSAD_oracle = kgraph::VectorOracle<std::vector<typeECSAD>, typeECSAD>;
		kgraph_ECSAD_oracle oracle_fI(m_FeaturesSet[fi], fn_l2_euclid);
		kgraph_ECSAD_oracle oracle_fJ(m_FeaturesSet[fj], fn_l2_euclid);

		kgraph::KGraph  *index_fI = kgraph::KGraph::create();
		kgraph::KGraph  *index_fJ = kgraph::KGraph::create();
		kgraph::KGraph::IndexParams params;

		index_fI->build(oracle_fI, params, NULL);
		index_fJ->build(oracle_fJ, params, NULL);`

I am not sure that I did it in the right way.

Anyway, it makes the distance between two data during the index building.

But, I have a problem.

It holds at parallel_try_insert in sudden.
It's ok couple of times, but suddenly it stops

Environment: visual studio 2013 update 5, win7 64bit

   
```
       unsigned parallel_try_insert (unsigned id, float dist) {
                if (dist > radius) return pool.size();
                LockGuard guard(lock);
                unsigned l = UpdateKnnList(&pool[0], L, Neighbor(id, dist, true));
                if (l <= L) { // inserted
                    if (L + 1 < pool.size()) { // if l == L + 1, there's a duplicate
                        ++L;
                    }
                    else {
                        radius = pool[L-1].dist;
                    }
                }
                return l;
            }

```

**Comment by aaalgo** [comment]
It appears that there's deadlock.  Please disable openmp when you compile the code and see if it still stucks.  I don't have a windows development environment and cannot reproduce the bug.  But with 1000s of data points, brutal force will be fast enough and KGraph probably won't help improve speed.

**Comment by eclipse0922** [comment]
I changed lockguard into EnterCriticalSection and LeaveCriticalSection. Then, it worked properly.
search performance is better than flann but, indexing performance is low.  I need to figure out proper parameter setting for my situation.

**Comment by aaalgo** [comment]
Thanks for figuring out that spin lock doesn't work properly in windows.

I still doubt the necessity of index given your small number of objects.  SearchOracle::search implements brute-force search without using index.  I suggest that you compare against that to make sure index helps.

**Comment by eclipse0922** [comment]
I know the brutal force is faster when I dealing with small data set.

 But I'm not sure that I keep dealing with those kinds of dataset only, 
maybe I have to deal with the large dataset( 200k ~ 300k * 3dim or 33 dim )

Anyway, I will try what you said. 



Here is Result for the same dataset.

Index O openMP O   3200ms
Index O openMP X   1800ms
Index X  openMP X    800ms

still longer than flann.

you're right.. 

But for OpenMP option, very weird.

Used dataSet: A, B both 7000 * 33 dim

indexparam.k= 1; //only one neighbor which is nearest to query data;

**Comment by eclipse0922** [comment]
```
              std::vector<std::array<float,33>> m_FeaturesSet_FPFH ;
            ~
           put some datat into featuredataset_fpfh
           ~
		using typeFPFH = std::array<float, 33>;
		auto fn_l2_euclid = [](typeFPFH const &a, typeFPFH const &b)
		{
			float sum = 0.0f;
			for (int i = 0; i < a.size(); i++)
			{
				sum += pow((a[i] - b[i]), 2);
			}
			sum = sqrt(sum);
			return sum;

		};
	        using kgraph_FPFH_oracle = kgraph::VectorOracle<std::vector<typeFPFH>, typeFPFH>;
		kgraph_FPFH_oracle oracle_fI(m_FeaturesSet_FPFH[fi], fn_l2_euclid);

	oracle_fI.query(m_FeaturesSet_FPFH[fj][j]).search(1U, 1e30f, &corres_K[0]);
      ~~
        oracle_fJ.query(m_FeaturesSet_FPFH[fi][i]).search(1U, 1e30f, &corres_K[0]);
```

**Comment by aaalgo** [comment]
Even though you are looking for k=1, you still want indexparam.k > 1, maybe 20.  This is confusing as k for index means to build a k-NN graph, no matter how the graph is to be used, rather than to build a ?-NN graph to be used as an index for k-NN search.  Successful searching depends on good connectivity of the graph, therefore you need k >> 1 for indexing.  Also, if you are using L2 distance, you might want to try my hand-vectorized implementation float_l2sqr_sse2,  here: https://github.com/aaalgo/kgraph/blob/master/kgraph-data.h .  The AVX version doesn't always work if your data address is not properly aligned.  If you want the AVX version, you'll need to put data into kgraph::Matrix(rows, cols), and pad 0s to your feature vectors so they have 36 dimensions (divisible by 4).  AVX doesn't speed up much over SSE2 on machines I've tested and it's probably not worth the effort.

As of OpenMP, there's an overhead, and it's only enabled in index construction.  I used spinlock for synchronization because the protected operations are too small, and executed too frequently to get OS involved.  If you switch to CriticalSection in Windows, it will substantially slow-down the computation for sure. Usually indexes are constructed once and used many many times.  In such cases, directly adding indexing time and search time is not very meaningful.

I'm sorry that this is getting complicated.

**Comment by eclipse0922** [comment]
Thank you for continuous help.

I need to try another lock method and vectorization. and more things for better performance.

As you said, it's not about vector oracle problem any more.
Getting complicated.. need to think a lot of things.
