### ISSUE TITLE
performance regressions

### ISSUE THREAD

**Issue by erikbern** [aaalgo/kgraph#9]
I'm rerunning ann-benchmarks and I'm seeing some issues with kgraph. Not sure what's going on but thought I'd mention it. Basically queries are very slow now

![image](https://cloud.githubusercontent.com/assets/1027979/12804471/a068d364-cac1-11e5-8cd8-4d8c5d4691f6.png)

**Comment by musicformellons** [comment]
Is this a bug? Can a fix be expected anytime soon? Greatly appreciated.

**Comment by aaalgo** [comment]
I'll work on this next week.

**Comment by aaalgo** [comment]
Just did a quick test with a fresh github fork.  Had to remove the link option "-static" to compile on my new machine, but didn't see any performance issue with the C++ API.  I'll look into Erik's benchmark later.

**Comment by aaalgo** [comment]
The performance regression was due to an optimization in the python API which trades a fixed per-batch overhead for fast average search speed.  When evaluated with batch size 1, there's no way to amortize the overhead.  The pykgraph implementation has been substantially modified to solve this performance issue.  C++ API was not affected by this bug.

**Comment by erikbern** [comment]
thanks a lot for looking into this!
